# Site settings
title: INTERSECT 2025
description: An annual symposium for Indonesian academics, practitioners, and policy-makers in sustainability, tech, & society
baseurl: ""
url: "https://intersect.id"

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

# Redirect settings
redirect_from:
  json: false

# Files to exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore

